spring:
  shardingsphere:
    enabled: true #启用
    datasource:
      names: m1,s1
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.130:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: root
        maxPoolSize: 50
        minPoolSize: 20
        maintenanceIntervalMilliseconds: 30000
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
      s1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.8:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: root
        maxPoolSize: 50
        minPoolSize: 20
        maintenanceIntervalMilliseconds: 30000
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
    rules:
      readwrite-splitting: # 配置读写分离规则
        data-sources:
          ds_0: # 给一套集群起个名
            type: static
            props:
              auto-aware-data-source-name: m1
              write-data-source-name: m1
              read-data-source-names: s1
            load-balancer-name: read-random
        load-balancers:
          read-random:
            type: ROUND_ROBIN # 轮询负载均衡
    props:
      sql-show: true #是否打印sql
      sql-simple: true #是否简单sql